config:
  newlic:apiKey:
    secure: AAABADDLI81dHqiUVeYn0sJ1T4tWgsJS1A0xqUTh1K3n1bPWN36SQKLOGoOq+xC/NkFZqNDngL62t2aouARXSsxGq6Gf0K4p
  newrelic:accountId: "3347353"
  newrelic:adminApiKey:
    secure: AAABAFJ4dpD9iUBESXdfLuIFzPv3VUDVsb1sdS3RVUw/XtsQFtCc7JqzIhTPUKjBuo90TD7F3Y+6tThQVVvH2A==
  newrelic:skip_initial_validation: "true"
